<?xml version="1.0" encoding="UTF-8"?>
<testng-results ignored="0" total="5" passed="4" failed="1" skipped="0">
  <reporter-output>
  </reporter-output>
  <suite started-at="2023-12-11T20:24:34 ICT" name="Default suite" finished-at="2023-12-11T20:24:39 ICT" duration-ms="4540">
    <groups>
    </groups>
    <test started-at="2023-12-11T20:24:34 ICT" name="Default test" finished-at="2023-12-11T20:24:39 ICT" duration-ms="4540">
      <class name="com.api.auto.testcase.TC_API_Login">
        <test-method is-config="true" signature="init()[pri:0, instance:com.api.auto.testcase.TC_API_Login@618b19ad]" started-at="2023-12-11T20:24:34 ICT" name="init" finished-at="2023-12-11T20:24:39 ICT" duration-ms="4354" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- init -->
        <test-method signature="TC01_Status()[pri:0, instance:com.api.auto.testcase.TC_API_Login@618b19ad]" started-at="2023-12-11T20:24:39 ICT" name="TC01_Status" finished-at="2023-12-11T20:24:39 ICT" duration-ms="15" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- TC01_Status -->
        <test-method signature="TC02_ValidateMessage()[pri:1, instance:com.api.auto.testcase.TC_API_Login@618b19ad]" started-at="2023-12-11T20:24:39 ICT" name="TC02_ValidateMessage" finished-at="2023-12-11T20:24:39 ICT" duration-ms="37" status="FAIL">
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[expected [??ng nh?p th�nh c�ng] but found [Đăng nhập thành công]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: expected [??ng nh?p th�nh c�ng] but found [Đăng nhập thành công]
at org.testng.Assert.fail(Assert.java:111)
at org.testng.Assert.failNotEquals(Assert.java:1578)
at org.testng.Assert.assertEqualsImpl(Assert.java:150)
at org.testng.Assert.assertEquals(Assert.java:132)
at org.testng.Assert.assertEquals(Assert.java:656)
at org.testng.Assert.assertEquals(Assert.java:666)
at com.api.auto.testcase.TC_API_Login.TC02_ValidateMessage(TC_API_Login.java:88)
at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:104)
at java.base/java.lang.reflect.Method.invoke(Method.java:578)
at org.testng.internal.invokers.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:139)
at org.testng.internal.invokers.TestInvoker.invokeMethod(TestInvoker.java:664)
at org.testng.internal.invokers.TestInvoker.invokeTestMethod(TestInvoker.java:227)
at org.testng.internal.invokers.MethodRunner.runInSequence(MethodRunner.java:50)
at org.testng.internal.invokers.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:957)
at org.testng.internal.invokers.TestInvoker.invokeTestMethods(TestInvoker.java:200)
at org.testng.internal.invokers.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:148)
at org.testng.internal.invokers.TestMethodWorker.run(TestMethodWorker.java:128)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
at org.testng.TestRunner.privateRun(TestRunner.java:848)
at org.testng.TestRunner.run(TestRunner.java:621)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:443)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:437)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:397)
at org.testng.SuiteRunner.run(SuiteRunner.java:336)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:95)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1280)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1200)
at org.testng.TestNG.runSuites(TestNG.java:1114)
at org.testng.TestNG.run(TestNG.java:1082)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- TC02_ValidateMessage -->
        <test-method signature="TC03_ValidateToken()[pri:2, instance:com.api.auto.testcase.TC_API_Login@618b19ad]" started-at="2023-12-11T20:24:39 ICT" name="TC03_ValidateToken" finished-at="2023-12-11T20:24:39 ICT" duration-ms="4" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- TC03_ValidateToken -->
        <test-method signature="TC05_ValidateUserType()[pri:3, instance:com.api.auto.testcase.TC_API_Login@618b19ad]" started-at="2023-12-11T20:24:39 ICT" name="TC05_ValidateUserType" finished-at="2023-12-11T20:24:39 ICT" duration-ms="20" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- TC05_ValidateUserType -->
        <test-method signature="TC06_ValidateAccount()[pri:4, instance:com.api.auto.testcase.TC_API_Login@618b19ad]" started-at="2023-12-11T20:24:39 ICT" name="TC06_ValidateAccount" finished-at="2023-12-11T20:24:39 ICT" duration-ms="29" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- TC06_ValidateAccount -->
        <test-method is-config="true" signature="afterClass()[pri:0, instance:com.api.auto.testcase.TC_API_Login@618b19ad]" started-at="2023-12-11T20:24:39 ICT" name="afterClass" finished-at="2023-12-11T20:24:39 ICT" duration-ms="1" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- afterClass -->
      </class> <!-- com.api.auto.testcase.TC_API_Login -->
    </test> <!-- Default test -->
  </suite> <!-- Default suite -->
</testng-results>
